endpoints:
  - hosts: worker-[1,2]
  - port-start: 18000

port:
  - 8001

load-balancer:
  workers: 20
  worker-concurrency: 512
  max-connections: 20000
  max-keepalive-connections: 4096
  upstream-timeout: 300
  log-dir: ~/.cache/llmup/logs
  affinity-db: ~/.cache/llmup/affinity.sqlite3
