endpoints:
  - worker-[41,45,49,53-54,57,59]:8000
  - setup: "direct"

port:
  - 8001

load-balancer:
  workers: 1
  worker-concurrency: 1024
  health-path: /v1/models
  log-dir: ~/.cache/llm-proxy/logs
  affinity-db: ~/.cache/llm-proxy/affinity.sqlite3

port-start: 18001
