endpoints:
  - worker-[41,45,49,53-54,57,59]:8000

port:
  - 8001

load-balancer:
  workers: 20
  worker-concurrency: 512
  health-path: /models
  log-dir: ~/.cache/llm-proxy/logs
  affinity-db: ~/.cache/llm-proxy/affinity.sqlite3

port-start: 18001
